version: '3.3'

services:
  nginx:
    image: nginx:1.19.4
    container_name: itsecurity-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  database:
    image: postgres:12.1
    container_name: itsecurity-postgres
    restart: unless-stopped
    volumes:
      - ./datait:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itsecurity
      PGDATA: /var/lib/postgresql/data/pgdata
  minio:
    image: minio/minio:RELEASE.2020-01-16T03-05-44Z
    command: server /data
    restart: unless-stopped
    expose:
      - '9000'
    volumes:
      - .data/minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    logging:
      driver: 'json-file'
      options:
        max-size: '500k'
        max-file: '10'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  backend:
    image: borsybela/itsecurity-backend:v9
    container_name: itsecurity-backend
    restart: unless-stopped
    expose:
      - '8080'
    environment:
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'postgres'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/itsecurity'
      ITSECURITY_WEB_HOST: 'localhost:8080'
      ITSECURITY_MINIO_ENDPOINT: http://minio:9000
    depends_on:
      - database
      - minio
