/**
 * ITSECURITY API documentation
 * ITSECURITY API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hu.bme.caffshare.data.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param id ID of the document, what is represent the CAFF
 * @param createdAt
 * @param creator
 */

@JsonClass(generateAdapter = true)
data class CaffSumDTO(
    /* ID of the document, what is represent the CAFF */
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "createdAt")
    val createdAt: java.time.LocalDateTime,
    @Json(name = "creator")
    val creator: kotlin.String
)

