/**
 * ITSECURITY API documentation
 * ITSECURITY API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hu.bme.caffshare.data.network.model


import com.squareup.moshi.Json

/**
 *
 * @param newPassword
 * @param currentPassword
 */

data class PasswordChangeDTO(
    @Json(name = "newPassword")
    val newPassword: kotlin.String,
    @Json(name = "currentPassword")
    val currentPassword: kotlin.String? = null
)

