/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mori5_itsecurity_cpp_CPPParserCaller */

#ifndef _Included_com_mori5_itsecurity_cpp_CPPParserCaller
#define _Included_com_mori5_itsecurity_cpp_CPPParserCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mori5_itsecurity_cpp_CPPParserCaller
 * Method:    parse
 * Signature: ([B)Lcom/mori5/itsecurity/cpp/CreatorsImages;
 */
JNIEXPORT jobject JNICALL Java_com_mori5_itsecurity_cpp_CPPParserCaller_parse
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
